name: my_weather_app
version: 1.0.0
config-version: 2
profile: my_weather_app

model-paths:
  - models
analysis-paths:
  - analyses
test-paths:
  - tests
seed-paths:
  - seeds
macro-paths:
  - macros
snapshot-paths:
  - snapshots

models:
  my_weather_app:
    +database: SNOWFLAKE_LEARNING_DB
    bronze:
      +schema: bronz
      +materialized: view
    silver:
      +schema: silver
      +materialized: view
    gold:
      +schema: gold
      +materialized: table
