my_weather_app:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: ${SNOWFLAKE_ACCOUNT}
      user: ${SNOWFLAKE_USER}
      password: ${SNOWFLAKE_PASSWORD}
      role: ACCOUNTADMIN
      warehouse: COMPUTE_WH
      database: WEATHER_DB
      schema: PUBLIC
