USE DATABASE WEATHER_DB;

SET weather_raw = 'WEATHER_DB.RAW.WEATHER';
SET weather_stage = 'WEATHER_DB.RAW.UPLOADS';
SET csv_file_format = 'WEATHER_CSV';
SET json_file_format = 'JSON';

CREATE FILE FORMAT IF NOT EXISTS IDENTIFIER($csv_file_format)
    TYPE = 'CSV'
    SKIP_HEADER = 1
    NULL_IF = ('NULL', '');

CREATE FILE FORMAT IF NOT EXISTS IDENTIFIER($json_file_format)
    TYPE = 'JSON';

COPY INTO IDENTIFIER($weather_raw) 
FROM (
    SELECT $1, METADATA$FILENAME, CURRENT_TIMESTAMP()
    FROM @WEATHER_DB.RAW.UPLOADS 
    (FILE_FORMAT => IDENTIFIER($json_file_format))
);


-- LIST @WEATHER_DB.RAW.UPLOADS